## A program to convert CSV files to numpy array

In [7]:
import numpy as np
arr=np.loadtxt("array.csv",dtype = float  ,delimiter=',') #Converts the text into multidimensional array
print(arr)

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
